# General Configuration
version: '{build}'
skip_branch_with_pr: true

init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Update-AppveyorBuild -Version "$spl.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

# Environment Configuration
image: Visual Studio 2017
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  # init and update submodules
  - git submodule update --recursive --init
  # update node.js to latest 8.x release
  - ps: Install-Product node 8
  - node --version
  - npm --version

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'

# Build Configuration
platform: Any CPU
configuration: Release

before_build:
  - nuget restore
  # nuget restore SpeckleCore/SpeckleCore/SpeckleCore.sln
  - mkdir %AppData%\Grasshopper\Libraries\SpeckleSendReceive
  - mkdir Release
  # install npm dependencies for SpeckleView and build
  - cd SpeckleView
  - npm install
  - npm run build
  # return to build dir
  - cd ..

build:
  project: SpeckleRhino.sln
  verbosity: minimal

after_build:
  # zip everything up into a .rhi package
  # - 7z a -tzip -r specklerhino.rhi "%APPVEYOR_BUILD_FOLDER%\SpeckleRhinoPlugin\SpeckleWinR6\bin\Release\*"
  # - 7z a -tzip -r specklerhino.rhi "%APPVEYOR_BUILD_FOLDER%\SpeckleGrasshopper\bin\Release\*"
  - 7z a -tzip -r SpeckleRhino-%APPVEYOR_BUILD_VERSION%.rhi "%APPVEYOR_BUILD_FOLDER%\Release\*"

artifacts:
- path: SpeckleRhino-%APPVEYOR_BUILD_VERSION%.rhi
  name: release

# deploy:
#   - release: SpeckleRhino-$(APPVEYOR_BUILD_VERSION)
#     tag: $(APPVEYOR_REPO_TAG_NAME)
#     #description: ''
#     provider: GitHub
#     auth_token:
#       secure: D5tPFvdQMg9sIe0sSvQjEWw4KAdOk1jyxNwiH5qP5DpDmUH6n6NgTdA+56vXS1Pe # your encrypted token from GitHub
#     artifact: SpeckleRhino-$(APPVEYOR_BUILD_VERSION).rhi
#     #draft: false
#     #prerelease: false
#     force_update: true
#     on:              # release from master branch only
#       appveyor_repo_tag: true        # deploy on tag push only

# notifications:
# - provider: Slack
#   incoming_webhook: 
#     secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
#   channel: '#devtalk'
#   template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
#   on_build_success: false
#   on_build_failure: true
#   on_build_status_changed: true
